name = "membership-sync-worker"
account_id = "394d48aba686b2466fe12e540c5d9466"
compatibility_date = "2022-04-30"
main = "index.mjs"

[vars]
AIRTABLE_BASE_ID = "appd1VGOi5zRgbI4Q"
AIRTABLE_TABLE_ID = "tblmYyqgRLZz49ofc"

# [secrets]
# STRIPE_WEBHOOK_SECRET
# AIRTABLE_SECRET
