name: Check

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  build:
    name: Check code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.79.1'

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup Node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.output.NVMRC }}"

      - name: Install dependencies
        run: npm ci

      - name: Check
        run: npm run check

      - name: Build
        run: npm run build
